### ISSUE TITLE
Projected completion incorrect

### ISSUE THREAD

**Issue by kalongthewires** [b2io/kubera#26]
The projected completion for a project seems incorrect. For example, when I look at Scopebuilder (TLE), the line seems to suggest that the team can complete > 400 points in 5 weeks when the team has an average velocity of 23 points (23 X 5 = 115 not 400).

Am I misunderstanding the chart?

**Comment by mewdriller** [comment]
My first thought is that it's probably taking stories that closed before the first sprint into account in a way we don't want it to. We can look over the test cases more closely, but I think that's probably the likeliest cause.

**Comment by mewdriller** [comment]
This is now captured in #29 which is in [Sprint 4](https://github.com/b2io/kubera/projects/5)'s ready column.
